import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {modules} from '@/content/modules';
import {resources} from '@/content/resources';
import {ModulePage,PlatformPage,SolutionsPage,AIPage,AboutPage,ResourceHub,ArticlePage,ContactPage,DemoPage,PolicyPage} from '@/components/site/pages';
import {AliasRedirect} from '@/components/site/alias-redirect';
import {sitePaths} from '@/content/routes';
import {siteOrigin} from '@/content/site';
const aliases:Record<string,string>={'Features':'/platform','Solutions':'/solutions','who-its-for':'/solutions','school-management-system':'/platform','login':'https://cleezoclass.com/CRM','cleezo-feedback':'/contact'};
const titles:Record<string,[string,string]>={'platform':['School Management Platform','Explore Cleezo Class modules for attendance, academics, school communication, finance, transport and daily operations.'],'solutions':['School Management for Every Role','Explore the Cleezo Class experience for school leaders, administrators, teachers and parents.'],'ai':['AI & Automation for School Workflows','Explore Cleezo Class’s published AI assistance for timetable planning, homework and assessment preparation, with human review.'],'about':['About Cleezo Class','Get to know Cleezo Class’s connected approach to school management and the people its workflows support.'],'resources':['Practical School Management Resources','Read practical guides for software evaluation, digital record planning and clearer parent communication.'],'contact':['Contact Cleezo Class','Contact the Cleezo Class team about product questions, school requirements and support enquiries.'],'book-demo':['Book a Cleezo Class Demo','Request a conversation about your school and explore relevant Cleezo Class workflows.'],'request-a-quote':['Request a School Software Quote','Discuss modules, school size and support needs to request a Cleezo Class quote.'],'privacy':['Website Privacy','How this website handles its demonstration forms.'],'terms':['Website Terms','Understand the website’s purpose, illustrative product previews and enquiry process.']};
export const dynamicParams=false;
export function generateStaticParams(){return [...sitePaths.filter(Boolean).map(path=>path.slice(1)),...Object.keys(aliases)].map(path=>({slug:path.split('/')}));}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const {slug}=await params;const path=slug.join('/');const m=slug[0]==='school-management-system'?modules.find(x=>x.slug===slug[1]):null;const a=slug[0]==='resources'?resources.find(x=>x.slug===slug[1]):null;const info=m?[m.title,m.intro]:a?[a.title,a.description]:titles[path]||[slug[0]==='solutions'?'Cleezo Class for '+({leaders:'School Leaders',administrators:'Administrators',teachers:'Teachers',parents:'Parents'} as Record<string,string>)[slug[1]]:'Page not found','Explore school workflows with Cleezo Class.'];return {title:info[0],description:info[1],alternates:{canonical:siteOrigin+'/'+path},openGraph:{title:info[0]+' | Cleezo Class',description:info[1],url:siteOrigin+'/'+path,type:'website'},twitter:{card:'summary',title:info[0]+' | Cleezo Class',description:info[1]}}}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const path=slug.join('/');if(aliases[path])return <AliasRedirect href={aliases[path]}/>;let page:React.ReactNode=null;if(slug.length===2&&slug[0]==='school-management-system'){const m=modules.find(x=>x.slug===slug[1]);if(m)page=<ModulePage module={m}/>;}else if(slug.length===2&&slug[0]==='resources'){if(resources.some(x=>x.slug===slug[1]))page=<ArticlePage slug={slug[1]}/>;}else if(slug[0]==='solutions'&&(slug.length===1||(slug.length===2&&['leaders','administrators','teachers','parents'].includes(slug[1]))))page=<SolutionsPage role={slug[1]}/>;else switch(path){case 'platform':page=<PlatformPage/>;break;case 'ai':page=<AIPage/>;break;case 'about':page=<AboutPage/>;break;case 'resources':page=<ResourceHub/>;break;case 'contact':page=<ContactPage/>;break;case 'book-demo':page=<DemoPage/>;break;case 'request-a-quote':page=<DemoPage quote/>;break;case 'privacy':case 'terms':page=<PolicyPage type={path}/>;break;}if(!page)notFound();const crumbs={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:siteOrigin},...slug.map((s,i)=>({'@type':'ListItem',position:i+2,name:titles[slug.slice(0,i+1).join('/')]?.[0]||s.replaceAll('-',' '),item:siteOrigin+'/'+slug.slice(0,i+1).join('/')}))]};return <main id="main">{page}<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(crumbs).replace(/</g,'\\u003c')}}/></main>}
