'use client';
import {useEffect,useRef,useState} from 'react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {ArrowDown,Check,BookOpen,PencilLine} from 'lucide-react';
import {ProductCanvas} from './product';
import {Action,Eyebrow,TextLink} from './ui';
import {ScrollJourney,ModuleVisual} from './experience';
import {modules,modulePath} from '@/content/modules';
export function HeroSequence(){const [mode,setMode]=useState(0);useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const trigger=ScrollTrigger.create({trigger:".hero-product-track",start:"top 25%",onEnter:()=>setMode(1),onLeaveBack:()=>setMode(0)});return()=>trigger.kill()},[]);return <section className="cinema-hero"><div className="hero-opening wrap"><Eyebrow>School management, thoughtfully connected</Eyebrow><h1><span className="headline-mask"><span>More time for education.</span></span><span className="headline-mask"><span>Less work around it.</span></span></h1><div className="hero-bottom"><p>Bring attendance, academics, fees and parent communication into one clear school management experience. A more coordinated team. A clearer view of the day.</p><div className="hero-actions"><Action/><Action href="/platform" secondary>Explore the Platform</Action></div></div><a className="scroll-cue mono" href="#school-day"><span>DISCOVER THE CONNECTED SCHOOL DAY</span><ArrowDown size={16}/></a></div><div className="hero-product-track"><div className="hero-product-frame wrap"><div className="hero-canvas-label"><span className="mono">YOUR SCHOOL DAY, AT A GLANCE</span><span className="mono">FROM THE FIRST BELL TO THE LAST UPDATE</span></div><ProductCanvas mode={mode}/><div className="hero-connection"><span className="mono">ATTENDANCE</span><i/><span className="mono">LEARNING</span><i/><span className="mono">PEOPLE</span><i/><span className="mono">ONE SCHOOL DAY</span></div></div></div></section>}
export function ModuleStory(){return <ScrollJourney kind="platform" steps={modules.map((m,i)=>({time:`0${i+1}`,label:m.label,title:m.title,body:m.intro,link:modulePath(m.slug)}))}>{active=><ModuleVisual module={modules[active]} step={Math.min(active%3,2)}/>}</ScrollJourney>}
const aiSteps=[
{time:'01',label:'Input',title:'Start with a teaching goal.',body:'A teacher provides a subject, topic and the kind of task they want to prepare. A clear request gives the suggestion a useful starting point.'},
{time:'02',label:'Context',title:'Bring the classroom into focus.',body:'Add relevant requirements, such as the class, syllabus coverage or difficulty. Ask which information each AI capability actually uses.'},
{time:'03',label:'Assistance',title:'Make room for a first draft.',body:'Explore a homework suggestion, a question-paper draft or a proposed timetable. Treat the output as material for a professional review.'},
{time:'04',label:'Review',title:'Look closely before it goes further.',body:'Check accuracy, age suitability, curriculum fit and practical constraints. An answer that reads well still needs careful judgement.'},
{time:'05',label:'Human decision',title:'Make the work your own.',body:'Edit, reject or choose a suggestion according to your school’s process. Confirm the actual editing and approval controls during the demo.'},
{time:'06',label:'Action',title:'Return to the school day.',body:'Use the reviewed material in the appropriate learning or planning workflow. Agree who remains responsible for the final result.'}
];
function AIWorkspace({step}:{step:number}){return <div className={`ai-document ai-state-${step}`}><div className="ai-document-head"><PencilLine size={19}/><span>Teaching preparation</span><span className="record-status">{step<2?'Input':step<4?'Draft':step===4?'Human review':'Ready to use'}</span></div><div className="ai-document-body"><span className="mono">ILLUSTRATIVE REVIEW PROCESS</span><div className="ai-brief"><span className="mono">THE TEACHER’S BRIEF</span><p>Help me prepare an observation task about plants for Class 6.</p><div className="ai-context"><span>Science</span><span>Our environment</span><span>Class 6</span></div></div><div className={`ai-draft ${step>=2?'draft-ready':''}`}><span className="mono">A SUGGESTION TO REVIEW</span><h3>Observe a plant.<br/>Tell its story.</h3><p>Record three observations. Add a labelled sketch. Write one question you would like to explore.</p><div className="ai-review-note"><PencilLine size={16}/><p>Teacher’s addition: use a plant you can observe safely at home or at school.</p></div></div><div className="ai-review-checks">{['Accurate and relevant','Suitable for the class','Reviewed by a teacher'].map((x,i)=><span key={x} className={step>=3+i?'checked':''}><i>{step>=3+i&&<Check size={12}/>}</i>{x}</span>)}</div><div className="ai-decision"><span className="mono">{aiSteps[step].label}</span><strong>{step===5?'People decide what goes into the lesson.':'A suggestion is a starting point.'}</strong></div></div></div>}
export function AIStory({full=false}:{full?:boolean}){return <section className="ai-scroll-section section"><div className="wrap"><Eyebrow>04 / AI assistance</Eyebrow><div className="section-heading"><h2>AI assists.<br/><span>People decide.</span></h2><div><p>Cleezo Class describes AI assistance for timetable planning, homework suggestions and question-paper preparation. Keep professional judgement at the centre.</p>{!full&&<TextLink href="/ai">Explore AI & Automation</TextLink>}</div></div><ScrollJourney kind="ai" steps={aiSteps}>{active=><AIWorkspace step={active}/>}</ScrollJourney></div></section>}
