'use client';
import {useState,useRef,useEffect} from 'react';
import {ArrowUpRight,Check} from 'lucide-react';
import Link from 'next/link';
export function DemoForm({kind}:{kind:'demo'|'quote'}){
 const [complete,setComplete]=useState(false);
 const successRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(complete)successRef.current?.focus()},[complete]);
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(e.currentTarget.reportValidity())setComplete(true)}
 if(complete)return <div ref={successRef} className="form-success" role="status" tabIndex={-1}><span className="success-icon"><Check size={28}/></span><h3>Demo complete.</h3><p>This is a demonstration form. Nothing was sent or saved, and no appointment was booked.</p><p>To contact the team, email <a href="mailto:support@cleezoclass.com">support@cleezoclass.com</a>.</p><button type="button" className="button button-outline" onClick={()=>setComplete(false)}>Try the form again</button><Link href="/platform" className="text-link">Keep exploring <ArrowUpRight size={18}/></Link></div>;
return <form onSubmit={submit} className="demo-form"><p className="form-intro" role="note">Demo form only. Your entries are not sent or saved. Use sample details to try it.</p><div className="form-row"><label>Your name <span aria-hidden="true">*</span><input name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder="Full name"/></label><label>Your role <span aria-hidden="true">*</span><input name="role" autoComplete="organization-title" required minLength={2} maxLength={80} placeholder="e.g. School administrator"/></label></div><label>School name <span aria-hidden="true">*</span><input name="school" autoComplete="organization" required minLength={2} maxLength={160} placeholder="Your school or institution"/></label><label>Work email <span aria-hidden="true">*</span><input name="email" type="email" autoComplete="email" required maxLength={180} placeholder="you@yourschool.com"/></label><label>Contact number <span className="optional">optional</span><input name="phone" type="tel" autoComplete="tel" maxLength={30} pattern="[+0-9 ()-]{6,30}" placeholder="Include your country code"/></label><label>What would you like to explore? <span className="optional">optional</span><textarea name="message" maxLength={1500} rows={3} placeholder={kind==='quote'?'Your priorities, approximate student count and required modules':'The workflows or questions on your mind'}/></label><p className="form-privacy">Please use sample information only. <Link href="/privacy">How this demo works</Link>.</p><button type="submit" className="button">Try the {kind==='quote'?'quote':'demo'} form <ArrowUpRight size={18}/></button><p className="form-small">Required fields are marked *. This preview does not submit a request.</p></form>}
