'use client';
import {createContext,useContext,useEffect,useRef,useState,type RefObject} from 'react';
import {usePathname} from 'next/navigation';
import {Pause,Play} from 'lucide-react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
const MotionContext=createContext(false);
export function useMotionDisabled(){return useContext(MotionContext)}
export function MotionProvider({children}:{children:React.ReactNode}){const [paused,setPaused]=useState(false);const [reduced,setReduced]=useState(false);useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setReduced(media.matches);sync();media.addEventListener('change',sync);try{setPaused(sessionStorage.getItem('cleezo-motion')==='paused')}catch{}return()=>media.removeEventListener('change',sync)},[]);const disabled=paused||reduced;return <MotionContext.Provider value={disabled}><div className={disabled?'site-motion motion-paused':'site-motion'}>{children}</div><button className="motion-toggle" onClick={()=>{setPaused(!paused);try{sessionStorage.setItem('cleezo-motion',!paused?'paused':'playing')}catch{}}} aria-pressed={disabled} disabled={reduced} aria-label={reduced?'Reduced motion is enabled':paused?'Resume motion':'Pause motion'}>{disabled?<Play size={13}/>:<Pause size={13}/>}<span>{reduced?'Reduced motion':paused?'Resume motion':'Pause motion'}</span></button></MotionContext.Provider>}
export function useStory(root:RefObject<HTMLElement|null>){const [active,setActive]=useState(0);const disabled=useContext(MotionContext);useEffect(()=>{if(!root.current||disabled)return;gsap.registerPlugin(ScrollTrigger);const el=root.current;const context=gsap.context(()=>{const steps=gsap.utils.toArray<HTMLElement>('.story-step',el);const sync=()=>{let index=0;steps.forEach((step,i)=>{if(step.getBoundingClientRect().top<=innerHeight*.54)index=i});setActive(index)};steps.forEach((step,i)=>{ScrollTrigger.create({trigger:step,start:'top 54%',end:'bottom 54%',onEnter:()=>setActive(i),onEnterBack:()=>setActive(i)});});gsap.fromTo(el,{'--journey':0},{'--journey':1,ease:'none',scrollTrigger:{trigger:el,start:'top center',end:'bottom center',scrub:true,onUpdate:sync,onRefresh:sync}});sync();document.fonts.ready.then(()=>{if(el.isConnected)sync()});const media=gsap.matchMedia();media.add('(max-width: 999px) and (prefers-reduced-motion: no-preference)',()=>{gsap.utils.toArray<HTMLElement>('.mobile-scene',el).forEach(scene=>{gsap.from(scene,{clipPath:'inset(0 0 8% 0)',scale:.985,transformOrigin:'center top',duration:.6,ease:'power2.out',scrollTrigger:{trigger:scene,start:'top 92%',once:true}});});});},el);return()=>context.revert()},[disabled,root]);return {active,disabled}}
export function MotionSetup(){const path=usePathname();const disabled=useContext(MotionContext);useEffect(()=>{if(disabled)return;gsap.registerPlugin(ScrollTrigger);const context=gsap.context(()=>{const media=gsap.matchMedia();media.add('(prefers-reduced-motion: no-preference)',()=>{gsap.utils.toArray<HTMLElement>('.photo-moment').forEach(el=>{gsap.fromTo(el.querySelector('figure'),{clipPath:'inset(9% 7% 9% 7%)'},{clipPath:'inset(0% 0% 0% 0%)',ease:'none',scrollTrigger:{trigger:el,start:'top 90%',end:'center 48%',scrub:.4}});gsap.fromTo(el.querySelector('img'),{scale:1.07,yPercent:-3},{scale:1,yPercent:3,ease:'none',scrollTrigger:{trigger:el,start:'top bottom',end:'bottom top',scrub:.5}});});gsap.utils.toArray<HTMLElement>('.section-heading h2,.about-manifesto h2').forEach(el=>{gsap.from(el,{clipPath:'inset(0 0 100% 0)',duration:.85,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}});});gsap.utils.toArray<HTMLElement>('.capability-list>div,.ai-use,.hub-articles>a').forEach(el=>{gsap.from(el,{clipPath:'inset(0 12% 0 0)',duration:.65,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 90%',once:true}});});gsap.utils.toArray<HTMLElement>('.closing').forEach(el=>{gsap.from(el.querySelectorAll('.closing-track span'),{y:24,opacity:.25,stagger:.09,duration:.7,scrollTrigger:{trigger:el,start:'top 80%',once:true}});});});media.add('(min-width: 1000px) and (prefers-reduced-motion: no-preference)',()=>{const hero=document.querySelector('.hero-product-track');if(hero){gsap.fromTo('.hero-product-frame',{scale:.88,rotateX:6,y:24},{scale:1,rotateX:0,y:0,ease:'none',scrollTrigger:{trigger:hero,start:'top 88%',end:'top 12%',scrub:.6}});gsap.to('.scroll-cue',{opacity:0,ease:'none',scrollTrigger:{trigger:'.cinema-hero',start:'top top',end:'25% top',scrub:true}});}});});return()=>context.revert()},[path,disabled]);return null}
